net:
  bindIp: 192.168.103.100,localhost
  port: 27000

storage:
  dbPath: /var/mongodb/db/

systemLog:
  path: /var/mongodb/db/mongod.log
  destination: file
  logAppend: true

processManagement:
  fork: true
  
operationProfiling:
  mode: slowOp
  slowOpThresholdMs: 50

security:
  authorization: enabled
